# Generated by Django 6.0.6 on 2026-07-15 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarMemo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("memo_date", models.DateField(verbose_name="메모 날짜")),
                ("content", models.TextField(blank=True, verbose_name="메모 내용")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_memos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "달력 메모",
                "verbose_name_plural": "달력 메모",
                "ordering": ["memo_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "memo_date"),
                        name="unique_calendar_memo_per_user_date",
                    )
                ],
            },
        ),
    ]
