# Generated by Django 6.0.6 on 2026-07-15 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="calendarmemo",
            table="calendar_memo",
        ),
    ]
