apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: pharmaflow-dev
  labels:
    app: pharmaflow-mariadb

spec:
  replicas: 1

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: pharmaflow-mariadb

  template:
    metadata:
      labels:
        app: pharmaflow-mariadb

    spec:
      containers:
        - name: mariadb
          image: mariadb:11
          imagePullPolicy: IfNotPresent

          ports:
            - name: mysql
              containerPort: 3306

          env:
            - name: MARIADB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: pharmaflow-config
                  key: DB_NAME

            - name: MARIADB_USER
              valueFrom:
                configMapKeyRef:
                  name: pharmaflow-config
                  key: DB_USER

            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pharmaflow-secret
                  key: DB_PASSWORD

            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pharmaflow-secret
                  key: MARIADB_ROOT_PASSWORD

          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql

          readinessProbe:
            exec:
              command:
                - healthcheck.sh
                - --connect
                - --innodb_initialized
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            exec:
              command:
                - healthcheck.sh
                - --connect
                - --innodb_initialized
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-data
