apiVersion: v1
kind: PersistentVolume
metadata:
  name: pharmaflow-mariadb-pv
  labels:
    app: pharmaflow-mariadb
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pharmaflow-local
  local:
    path: /srv/pharmaflow-k8s/mariadb
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - wk1
