apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data
  namespace: pharmaflow-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: pharmaflow-local
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      app: pharmaflow-mariadb
