apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: pharmaflow-dev
spec:
  type: ClusterIP
  selector:
    app: pharmaflow-mariadb
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
