# Generated by Django 6.0.6 on 2026-07-13 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmacy',
            options={'verbose_name': '약국', 'verbose_name_plural': '약국'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '사용자', 'verbose_name_plural': '사용자'},
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='external_place_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='외부 장소 ID'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='위도'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='경도'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='business_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='사업자명'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='business_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='사업자등록번호'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록일'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='owner_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='대표자명'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='대표 연락처'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '운영 중'), ('SUSPENDED', '휴업'), ('CLOSED', '폐업')], default='ACTIVE', max_length=20, verbose_name='운영 상태'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='승인 여부'),
        ),
        migrations.AlterField(
            model_name='user',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='약사 면허번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.pharmacy', verbose_name='소속 약국'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='연락처'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', '관리자'), ('PHARMACIST', '약사'), ('STAFF', '직원')], default='STAFF', max_length=20, verbose_name='역할'),
        ),
    ]
