# Generated by Django 6.0.6 on 2026-07-13 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_pharmacy_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='data_source',
            field=models.CharField(choices=[('HIRA', '건강보험심사평가원'), ('MANUAL', '직접 등록')], default='MANUAL', max_length=20, verbose_name='데이터 출처'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='공식 데이터 확인'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='external_place_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='외부 약국 식별값'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='승인 여부'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', '점주'), ('PHARMACIST', '약사'), ('STAFF', '직원')], default='STAFF', max_length=20, verbose_name='역할'),
        ),
        migrations.CreateModel(
            name='PharmacyOwnershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_number', models.CharField(max_length=20, verbose_name='사업자등록번호')),
                ('status', models.CharField(choices=[('PENDING', '승인 대기'), ('APPROVED', '승인 완료'), ('REJECTED', '거절')], default='PENDING', max_length=20, verbose_name='처리 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신청일')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리일')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_requests', to='accounts.pharmacy', verbose_name='신청 약국')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_requests', to=settings.AUTH_USER_MODEL, verbose_name='신청자')),
            ],
            options={
                'verbose_name': '점주 권한 신청',
                'verbose_name_plural': '점주 권한 신청',
                'db_table': 'pharmacy_ownership_request',
                'constraints': [models.UniqueConstraint(fields=('user', 'pharmacy'), name='unique_user_pharmacy_ownership_request')],
            },
        ),
    ]
