# Generated by Django 6.0.6 on 2026-07-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pharmacy_data_source_pharmacy_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/', verbose_name='프로필 사진'),
        ),
    ]
