# Generated by Django 6.0.6 on 2026-07-20 07:29

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="pharmacyownershiprequest",
            name="business_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="사업자명"
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="business_number",
            field=models.CharField(
                blank=True,
                help_text="000-00-00000 형식으로 입력해 주세요.",
                max_length=12,
                null=True,
                unique=True,
                validators=[accounts.validators.validate_business_number],
                verbose_name="사업자등록번호",
            ),
        ),
        migrations.AlterField(
            model_name="pharmacyownershiprequest",
            name="business_number",
            field=models.CharField(
                help_text="000-00-00000 형식으로 입력해 주세요.",
                max_length=12,
                validators=[accounts.validators.validate_business_number],
                verbose_name="사업자등록번호",
            ),
        ),
    ]
