# Generated by Django 6.0.6 on 2026-07-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_consultation_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='tag',
            field=models.CharField(choices=[('NOTICE', '공지'), ('CHAT', '잡담'), ('QUESTION', '질문'), ('COUNSEL', '상담'), ('INFO', '정보')], default='CHAT', max_length=10, verbose_name='태그'),
        ),
    ]
