# Generated by Django 6.0.6 on 2026-07-16 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_consultation_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='작업구분')),
                ('target', models.CharField(max_length=100, verbose_name='작업대상')),
                ('detail', models.TextField(verbose_name='상세내용 및 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작업시간')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작업자')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
