# Generated by Django 6.0.6 on 2026-07-13 08:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorytransaction',
            options={'ordering': ['-created_at'], 'verbose_name': '입출고 내역', 'verbose_name_plural': '입출고 내역'},
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='비고'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='처리일시'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.medicine', verbose_name='의약품'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='수량'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', '입고'), ('OUT', '출고')], max_length=3, verbose_name='입출고 구분'),
        ),
    ]
