# Generated by Django 6.0.6 on 2026-07-14 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pharmacy_data_source_pharmacy_is_verified_and_more'),
        ('inventory', '0002_alter_inventorytransaction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-created_at'], 'verbose_name': '발주', 'verbose_name_plural': '발주'},
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL, verbose_name='처리자'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='box_image',
            field=models.ImageField(blank=True, null=True, upload_to='medicines/boxes/', verbose_name='약 상자 이미지'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='medicine_image',
            field=models.ImageField(blank=True, null=True, upload_to='medicines/items/', verbose_name='약 이미지'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='accounts.pharmacy', verbose_name='약국'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ordered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='발주자'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='발주일'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='inventory.medicine', verbose_name='의약품'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='발주 수량'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('WAIT', '대기'), ('DONE', '완료'), ('CANCELLED', '취소')], default='WAIT', max_length=10, verbose_name='상태'),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.UniqueConstraint(fields=('pharmacy', 'name', 'manufacturer'), name='unique_medicine_per_pharmacy'),
        ),
    ]
