# Generated by Django 6.0.6 on 2026-07-14 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pharmacy_data_source_pharmacy_is_verified_and_more'),
        ('inventory', '0003_alter_purchaseorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='accounts.pharmacy', verbose_name='약국'),
        ),
    ]
