# Generated by Django 6.0.6 on 2026-07-14 08:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_medicine_pharmacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='비고'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='입고 완료일'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.medicine', verbose_name='의약품'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='발주 수량'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('WAIT', '발주 대기'), ('ORDERED', '발주 완료'), ('RECEIVED', '입고 완료'), ('CANCELLED', '취소')], default='WAIT', max_length=10, verbose_name='상태'),
        ),
    ]
