# Generated by Django 6.0.6 on 2026-07-13 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='medicine_name',
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='medicine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.medicine', verbose_name='처방 약품'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='total_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='총 처방 수량(알/포)'),
        ),
    ]
