# Generated by Django 6.0.6 on 2026-07-13 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationcomment',
            name='consultation',
        ),
        migrations.RemoveField(
            model_name='consultationcomment',
            name='writer',
        ),
        migrations.DeleteModel(
            name='Consultation',
        ),
        migrations.DeleteModel(
            name='ConsultationComment',
        ),
    ]
