# Generated by Django 6.0.6 on 2026-07-14 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pharmacy_data_source_pharmacy_is_verified_and_more'),
        ('prescriptions', '0005_prescription_created_at_prescription_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='pharmacy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.pharmacy', verbose_name='지정 약국'),
        ),
    ]
