# Generated by Django 6.0.6 on 2026-07-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0006_prescription_pharmacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='duration',
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='daily_doses',
            field=models.PositiveIntegerField(default=3, verbose_name='1일 투여횟수(회)'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='dose_amount',
            field=models.PositiveIntegerField(default=1, verbose_name='1회 투약량(알/포)'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='duration_days',
            field=models.PositiveIntegerField(default=3, verbose_name='투약일수(일)'),
        ),
    ]
