apiVersion: batch/v1
kind: Job
metadata:
  name: pharmaflow-django-migrate
  namespace: pharmaflow-dev
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-2"

spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3

  template:
    metadata:
      labels:
        app: pharmaflow-django-migrate

    spec:
      restartPolicy: Never

      securityContext:
        runAsNonRoot: true

      containers:
        - name: migrate
          image: REPLACE-WITH-DJANGO-ECR-REPOSITORY-URL:REPLACE-WITH-IMAGE-TAG
          imagePullPolicy: IfNotPresent

          securityContext:
            runAsUser: 999
            runAsGroup: 999

          envFrom:
            - configMapRef:
                name: pharmaflow-config
            - secretRef:
                name: pharmaflow-secret

          command:
            - python
            - manage.py
            - migrate
            - --noinput

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
