apiVersion: v1
kind: Service
metadata:
  name: django
  namespace: pharmaflow-dev
  labels:
    app: django

spec:
  type: ClusterIP

  selector:
    app: django

  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
