apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - django/migrate-job.yaml
  - django/collectstatic-job.yaml
  - django/deployment.yaml
  - django/service.yaml
  - django/hpa.yaml
  - django/pdb.yaml
  - nginx/deployment.yaml
  - nginx/service.yaml
  - nginx/configmap.yaml
  - nginx/pdb.yaml

images:
  - name: REPLACE-WITH-DJANGO-ECR-REPOSITORY-URL
    newName: 962450756907.dkr.ecr.ap-northeast-2.amazonaws.com/pharmaflow-django
    newTag: sha-88d51c80a3df12ab324ef4c39bc44fec34040d36

  - name: REPLACE-WITH-NGINX-ECR-REPOSITORY-URL
    newName: 962450756907.dkr.ecr.ap-northeast-2.amazonaws.com/pharmaflow-nginx
    newTag: sha-88d51c80a3df12ab324ef4c39bc44fec34040d36
